---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
  annotations:
    # Azure Load Balancer annotations for better control
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "your-resource-group"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: voting-app-pod
    app: demo-voting-app